services:
  # Backend API
  - type: web
    name: expense-tracker-api
    env: docker
    repo: https://github.com/voxuanthang68/devops_QLchitieu
    plan: free
    region: singapore
    dockerContext: .
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://devops_db_user:yUodWsQCtuDyU3R@cluster0.szujvoc.mongodb.net/expense-tracker?retryWrites=true&w=majority
      - key: NODE_ENV
        value: production

  # Frontend UI
  - type: web
    name: expense-tracker-ui
    env: docker
    repo: https://github.com/voxuanthang68/devops_QLchitieu
    plan: free
    region: singapore
    dockerContext: .
    dockerfilePath: frontend/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://expense-tracker-api-zxzj.onrender.com/api # Nginx will proxy this to the backend if configured, 
                    # but on Render, it's better to use the actual Backend URL.
